"""Fix relations

Revision ID: 4ae774cc1fbd
Revises: 9018fe92bbfe
Create Date: 2024-07-08 17:20:17.983102

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4ae774cc1fbd"
down_revision: Union[str, None] = "9018fe92bbfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
