"""[IMP] fix JSON mapping

Revision ID: 93cfeed09996
Revises: fcb28d98ad45
Create Date: 2024-06-05 21:10:49.626573

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "93cfeed09996"
down_revision: Union[str, None] = "fcb28d98ad45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
