"""[IMP] fix JSON mapping

Revision ID: a248f92e07e3
Revises: 93cfeed09996
Create Date: 2024-06-05 21:11:56.912934

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a248f92e07e3"
down_revision: Union[str, None] = "93cfeed09996"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
